name: ci
on: [push, pull_request]
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-go@v5
     with: {go-version: '1.23.x'}
   - uses: hashicorp/setup-terraform@v3
   - run: go test ./...
   - run: terraform -chdir=terraform fmt -check
   - run: terraform -chdir=terraform init -backend=false
   - run: terraform -chdir=terraform validate
   - run: bash tests/security.sh
